import type { DrillWord } from "@/lib/types";

export const wordBank: DrillWord[] = [
  {
    id: "verdant",
    word: "verdant",
    phonetic: "VUR-dunt",
    category: "warm-up",
    difficulty: 2,
    pronunciationNote: "Primary stress on the first syllable.",
    definition: "Green with vegetation or fresh growth.",
    sentence: "After the rain, the hills looked unusually green and lush.",
    origin: "From Latin through French, related to the idea of being green.",
    coachingNote: "Lock in ver- at the front and finish cleanly with -dant.",
    source: "local-seed",
  },
  {
    id: "echelon",
    word: "echelon",
    phonetic: "ESH-uh-lahn",
    category: "pressure",
    difficulty: 3,
    pronunciationNote: "The first syllable sounds like 'esh'.",
    definition: "A level or rank in an organization or system.",
    sentence: "She quickly moved into the highest rank of the student council.",
    origin: "From French, originally referring to a rung or ladder formation.",
    coachingNote: "The vowel pattern is the trap, not the final -lon.",
    source: "local-seed",
  },
  {
    id: "halcyon",
    word: "halcyon",
    phonetic: "HAL-see-uhn",
    category: "boss round",
    difficulty: 3,
    pronunciationNote: "Keep the middle syllable light and smooth.",
    definition: "Calm, peaceful, or prosperous, often when recalling an earlier time.",
    sentence: "They still talked about those calm and golden summers by the lake.",
    origin: "From Greek myth, linked to a bird associated with calm seas.",
    coachingNote: "The end looks heavier than it sounds. Stay relaxed through -cyon.",
    source: "local-seed",
  },
  {
    id: "clandestine",
    word: "clandestine",
    phonetic: "klan-DES-tin",
    category: "review",
    difficulty: 4,
    pronunciationNote: "Stress falls on the middle syllable.",
    definition: "Kept secret or done in a private, hidden way.",
    sentence: "Their private meeting was meant to stay hidden from the press.",
    origin: "From Latin, carrying the sense of secrecy.",
    coachingNote: "Do not lose the s in the middle cluster.",
    source: "local-seed",
  },
  {
    id: "auspicious",
    word: "auspicious",
    phonetic: "aw-SPISH-us",
    category: "warm-up",
    difficulty: 3,
    pronunciationNote: "The second syllable carries the stress.",
    definition: "Showing signs of future success or good fortune.",
    sentence: "The clear weather seemed like a lucky sign for the opening match.",
    origin: "From Latin, related to favorable omens.",
    coachingNote: "The sound says spish, but the spelling needs -spic-.",
    source: "local-seed",
  },
  {
    id: "gossamer",
    word: "gossamer",
    phonetic: "GAH-suh-mer",
    category: "warm-up",
    difficulty: 3,
    pronunciationNote: "Three light syllables with a soft middle vowel.",
    definition: "Something very light, thin, or delicate.",
    sentence: "The fabric looked so airy it almost floated in the window.",
    origin: "An old English word once linked with a fine autumn cobweb.",
    coachingNote: "The double s comes early, before the lighter ending.",
    source: "local-seed",
  },
  {
    id: "impetuous",
    word: "impetuous",
    phonetic: "im-PECH-oo-us",
    category: "pressure",
    difficulty: 4,
    pronunciationNote: "The stressed syllable lands in the middle.",
    definition: "Acting quickly and without enough thought.",
    sentence: "His rash decision came before anyone could warn him.",
    origin: "From Latin, connected to force or attack.",
    coachingNote: "Hear the ch sound, but remember the spelling keeps the t.",
    source: "local-seed",
  },
  {
    id: "loquacious",
    word: "loquacious",
    phonetic: "loh-KWAY-shus",
    category: "boss round",
    difficulty: 4,
    pronunciationNote: "The kw sound sits in the stressed syllable.",
    definition: "Very talkative.",
    sentence: "The usually chatty guest carried the conversation through dinner.",
    origin: "From Latin, tied to speaking.",
    coachingNote: "The q is followed by ua, not the simpler wa sound you hear.",
    source: "local-seed",
  },
  {
    id: "vicissitude",
    word: "vicissitude",
    phonetic: "vih-SIS-uh-tood",
    category: "boss round",
    difficulty: 5,
    pronunciationNote: "The middle syllable is stressed; the ending stays crisp.",
    definition: "A change in conditions, especially one that is difficult or unwelcome.",
    sentence: "The team handled every unexpected change with patience.",
    origin: "From Latin, referring to change or alternation.",
    coachingNote: "Double s in the middle, then slide carefully into -tude.",
    source: "local-seed",
  },
  {
    id: "labyrinth",
    word: "labyrinth",
    phonetic: "LAB-uh-rinth",
    category: "review",
    difficulty: 3,
    pronunciationNote: "The first syllable is strong; the ending is thin.",
    definition: "A maze or something highly intricate.",
    sentence: "The old palace halls felt like a maze with no clear exit.",
    origin: "From Greek, tied to the legendary maze of Crete.",
    coachingNote: "Keep the y after the lab- opening and land on -rinth.",
    source: "local-seed",
  },
  {
    id: "desiccate",
    word: "desiccate",
    phonetic: "DES-ih-kayt",
    category: "review",
    difficulty: 4,
    pronunciationNote: "The opening sounds plain, but the spelling doubles the c.",
    definition: "To dry out thoroughly.",
    sentence: "The intense heat can dry the soil until it cracks.",
    origin: "From Latin, meaning to dry up.",
    coachingNote: "The secret is the double c before the ending.",
    source: "local-seed",
  },
  {
    id: "panacea",
    word: "panacea",
    phonetic: "pan-uh-SEE-uh",
    category: "warm-up",
    difficulty: 3,
    pronunciationNote: "The see syllable is the peak.",
    definition: "A solution claimed to fix every problem.",
    sentence: "The new policy is useful, but it is not a cure-all.",
    origin: "From Greek, the name of a goddess associated with healing.",
    coachingNote: "The sound glides, but the spelling needs the full -acea ending.",
    source: "local-seed",
  },
  {
    id: "tenacious",
    word: "tenacious",
    phonetic: "tuh-NAY-shus",
    category: "warm-up",
    difficulty: 3,
    pronunciationNote: "Stress falls on the middle syllable.",
    definition: "Persistent and not easily letting go.",
    sentence: "The climber was determined and would not give up on the route.",
    origin: "From Latin, connected to holding firmly.",
    coachingNote: "After tena-, do not drift into an easier -shus spelling.",
    source: "local-seed",
  },
  {
    id: "mellifluous",
    word: "mellifluous",
    phonetic: "muh-LIF-loo-us",
    category: "boss round",
    difficulty: 5,
    pronunciationNote: "The middle syllable leads; keep the flow smooth after it.",
    definition: "Pleasantly smooth or musical in sound.",
    sentence: "Her voice was so sweet and flowing that the room went quiet.",
    origin: "From Latin, literally carrying the sense of honey and flow.",
    coachingNote: "Double l early, then fluous to the finish.",
    source: "local-seed",
  },
  {
    id: "sovereign",
    word: "sovereign",
    phonetic: "SOV-rin",
    category: "pressure",
    difficulty: 4,
    pronunciationNote: "The spoken form compresses more than the spelling suggests.",
    definition: "Independent in authority; also a supreme ruler.",
    sentence: "Each nation remains independent under its own laws.",
    origin: "From French and Latin, tied to supremacy.",
    coachingNote: "The hidden ei is what usually causes the miss.",
    source: "local-seed",
  },
  {
    id: "ubiquitous",
    word: "ubiquitous",
    phonetic: "yoo-BIK-wuh-tus",
    category: "pressure",
    difficulty: 4,
    pronunciationNote: "The second syllable takes the stress.",
    definition: "Present or appearing everywhere.",
    sentence: "Screens are now common in nearly every classroom and office.",
    origin: "From Latin, meaning everywhere.",
    coachingNote: "Start with ubi-, then keep the qu sequence intact.",
    source: "local-seed",
  },
  {
    id: "laconic",
    word: "laconic",
    phonetic: "luh-KAH-nik",
    category: "warm-up",
    difficulty: 2,
    pronunciationNote: "The middle syllable is broad and stressed.",
    definition: "Using very few words.",
    sentence: "His reply was so brief that nobody could read his mood.",
    origin: "From Laconia in ancient Greece, famous for brief speech.",
    coachingNote: "The opening is simple; do not overcomplicate the ending.",
    source: "local-seed",
  },
  {
    id: "beleaguer",
    word: "beleaguer",
    phonetic: "bih-LEE-ger",
    category: "review",
    difficulty: 4,
    pronunciationNote: "The middle syllable is the clearest one.",
    definition: "To trouble greatly or to surround in a hostile way.",
    sentence: "A long series of setbacks continued to trouble the campaign.",
    origin: "From Dutch, originally used in military siege language.",
    coachingNote: "Hear the hard g and remember the be- opening.",
    source: "local-seed",
  },
  {
    id: "cadenza",
    word: "cadenza",
    phonetic: "kuh-DEN-zuh",
    category: "warm-up",
    difficulty: 3,
    pronunciationNote: "The middle syllable is stressed.",
    definition: "A brilliant solo passage in a musical work.",
    sentence: "The soloist held the hall in suspense during the dazzling passage.",
    origin: "From Italian, tied to cadence and musical flow.",
    coachingNote: "The z is voiced, but the spelling stays elegant and clean.",
    source: "local-seed",
  },
  {
    id: "seraphic",
    word: "seraphic",
    phonetic: "suh-RAF-ik",
    category: "pressure",
    difficulty: 3,
    pronunciationNote: "Stress falls on the second syllable.",
    definition: "Pure, serene, or angelic.",
    sentence: "Her calm expression looked almost angelic in the morning light.",
    origin: "From a word for a high order of angels, through Latin and Greek.",
    coachingNote: "The ph keeps the f sound in the middle.",
    source: "local-seed",
  },
  {
    id: "diaphanous",
    word: "diaphanous",
    phonetic: "dy-AF-uh-nus",
    category: "boss round",
    difficulty: 5,
    pronunciationNote: "The second syllable opens up strongly.",
    definition: "Light, delicate, and almost transparent.",
    sentence: "The curtain was so sheer that morning light slipped through it.",
    origin: "From Greek, with a sense of showing through.",
    coachingNote: "Hear the f, spell the ph, and stay patient through the ending.",
    source: "local-seed",
  },
  {
    id: "obstreperous",
    word: "obstreperous",
    phonetic: "ub-STREP-er-us",
    category: "boss round",
    difficulty: 5,
    pronunciationNote: "The strep section is the anchor point.",
    definition: "Noisy and difficult to control.",
    sentence: "The crowd grew loud and unruly after the call on the field.",
    origin: "From Latin, tied to making a clamor.",
    coachingNote: "The opening cluster matters; do not simplify it to something easier.",
    source: "local-seed",
  },
  {
    id: "quandary",
    word: "quandary",
    phonetic: "KWON-duh-ree",
    category: "pressure",
    difficulty: 3,
    pronunciationNote: "The first syllable is round and clear.",
    definition: "A state of uncertainty or perplexity.",
    sentence: "She faced a real dilemma after both offers arrived the same day.",
    origin: "Likely from Latin through French, though the exact history is uncertain.",
    coachingNote: "The tricky move is from quan- into -dary without losing the a.",
    source: "local-seed",
  },
  {
    id: "indelible",
    word: "indelible",
    phonetic: "in-DEL-uh-bul",
    category: "review",
    difficulty: 3,
    pronunciationNote: "The second syllable carries the stress.",
    definition: "Not able to be removed or forgotten.",
    sentence: "The performance left a lasting mark on the entire audience.",
    origin: "From Latin, meaning unable to be erased.",
    coachingNote: "The center is straightforward; the quiet ending is what drifts.",
    source: "local-seed",
  },
  {
    id: "respite",
    word: "respite",
    phonetic: "RES-pit",
    category: "warm-up",
    difficulty: 2,
    pronunciationNote: "The spoken ending is shorter than the spelling looks.",
    definition: "A short period of rest or relief.",
    sentence: "The rain gave the workers a brief break from the heat.",
    origin: "From Latin through Old French, tied to delay or pause.",
    coachingNote: "The visible e at the end is the classic trap.",
    source: "local-seed",
  },
  {
    id: "vociferous",
    word: "vociferous",
    phonetic: "voh-SIF-er-us",
    category: "pressure",
    difficulty: 4,
    pronunciationNote: "The middle syllable is sharp and stressed.",
    definition: "Loud and forceful in expression.",
    sentence: "The fans became loudly outspoken after the final whistle.",
    origin: "From Latin, meaning to call out or shout.",
    coachingNote: "Keep the ci sequence even though the sound pushes you elsewhere.",
    source: "local-seed",
  },
];
